## 강의실 데이터 추가하기.
- 동아리방
- 학부방
- 식당

등

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
import pandas as pd
import numpy as np

In [2]:
basic_data_path = '/content/drive/MyDrive/mapinskhu(26~)/Data/26-2/basic_room_data.csv'
add_data_path = '/content/drive/MyDrive/mapinskhu(26~)/Data/26-2/add_room_data.csv'

In [12]:
bdf = pd.read_csv(basic_data_path)
adf = pd.read_csv(add_data_path) # 데이터 공개 x

NameError: name 'basic_data_path' is not defined

In [5]:
bdf

       kwan_name   room  floor  room_image  room_type
0           새천년관   7207      2         NaN        NaN
1           새천년관   7208      2         NaN        NaN
2            월당관   3402      4         NaN        NaN
3           새천년관   7308      3         NaN        NaN
4           새천년관   7309      3         NaN        NaN
5            승연관   1504      5         NaN        NaN
6            승연관   1503      5         NaN        NaN
7            승연관   1505      5         NaN        NaN
8            월당관   3502      5         NaN        NaN
9           미가엘관   M401      4         NaN        NaN
10         정보과학관   6206      2         NaN        NaN
11           월당관   3302      3         NaN        NaN
12         정보과학관   6201      2         NaN        NaN
13          미가엘관   M205      2         NaN        NaN
14         정보과학관   6110      1         NaN        NaN
15          미가엘관   M301      3         NaN        NaN
16          새천년관   7304      3         NaN        NaN
17          새천년관   7307      3         NaN        NaN
18          새천년관   7202      2         NaN        NaN
19          새천년관   7303      3         NaN        NaN
20          새천년관   7206      2         NaN        NaN
21          새천년관   7305      3         NaN        NaN
22          새천년관   7301      3         NaN        NaN
23          새천년관   7417      4         NaN        NaN
24          새천년관   7306      3         NaN        NaN
25          새천년관   7616      6         NaN        NaN
26           승연관   1501      5         NaN        NaN
27           승연관   1502      5         NaN        NaN
28         정보과학관   6404      4         NaN        NaN
29          미가엘관   M404      4         NaN        NaN
30          미가엘관   M406      4         NaN        NaN
31           승연관   1508      5         NaN        NaN
32           승연관   1507      5         NaN        NaN
33          미가엘관   M407      4         NaN        NaN
34          새천년관   7204      2         NaN        NaN
35           월당관   3301      3         NaN        NaN
36           월당관   3401      4         NaN        NaN
37           일만관   B105      1         NaN        NaN
38           월당관   3501      5         NaN        NaN
39          미가엘관   M402      4         NaN        NaN
40           승연관   1506      5         NaN        NaN
41          새천년관   7107      1         NaN        NaN
42          새천년관   7205      2         NaN        NaN
43  성미가엘성당&피츠버그홀   9301      3         NaN        NaN
44          미가엘관   M403      4         NaN        NaN
45           나눔관  5C301      3         NaN        NaN
46  성미가엘성당&피츠버그홀   9990      9         NaN        NaN
47          새천년관   7201      2         NaN        NaN
48         정보과학관   6406      4         NaN        NaN
49         정보과학관   6202      2         NaN        NaN
50         정보과학관   6405      4         NaN        NaN
51         정보과학관   6403      4         NaN        NaN
52         정보과학관   6402      4         NaN        NaN
53  성미가엘성당&피츠버그홀   9101      1         NaN        NaN
54          새천년관   7302      3         NaN        NaN
55         정보과학관   6109      1         NaN        NaN

In [6]:
adf

       용도구분     용도분류    건물명     층        호  실    세부용도
0    교육기본시설    실험실습실   구두인관   NaN      1A103    실험실습실
1    교육기본시설     대학본부   구두인관   NaN      1A101      사무실
2    교육기본시설     대학본부   구두인관   NaN      1A102      사무실
3    교육기본시설     대학본부   구두인관   NaN      1A104      사무실
4    교육기본시설     대학본부   구두인관   NaN      1A201      사무실
..      ...      ...    ...   ...         ...      ...
393    지원시설   학생기숙사   행복기숙사    6층     549.69      기숙사
394    지원시설   학생기숙사   행복기숙사    7층     549.69      기숙사
395    지원시설   학생기숙사   행복기숙사    8층     549.69      기숙사
396    지원시설   학생기숙사   행복기숙사    9층     549.69      기숙사
397    지원시설   학생기숙사   행복기숙사  지하1층   1,010.19      기숙사

[398 rows x 6 columns]

In [7]:
adf.columns = ['a', 'b', 'c', 'd', 'room', 'detail']
adf

          a        b      c     d        room   detail
0    교육기본시설    실험실습실   구두인관   NaN      1A103    실험실습실
1    교육기본시설     대학본부   구두인관   NaN      1A101      사무실
2    교육기본시설     대학본부   구두인관   NaN      1A102      사무실
3    교육기본시설     대학본부   구두인관   NaN      1A104      사무실
4    교육기본시설     대학본부   구두인관   NaN      1A201      사무실
..      ...      ...    ...   ...         ...      ...
393    지원시설   학생기숙사   행복기숙사    6층     549.69      기숙사
394    지원시설   학생기숙사   행복기숙사    7층     549.69      기숙사
395    지원시설   학생기숙사   행복기숙사    8층     549.69      기숙사
396    지원시설   학생기숙사   행복기숙사    9층     549.69      기숙사
397    지원시설   학생기숙사   행복기숙사  지하1층   1,010.19      기숙사

[398 rows x 6 columns]

# 필요한 컬럼만 남기기

1. 관, 층, 세부 만 남길 것이다. (kwan, room, detail)

2. adf에서 사용하는 관 이름이 맵인스쿠에서 사용하는 이름과 다르기에 맵인스쿠 이름과 동일하게 바꿔줄 것이다.

3. 세부는 해당 강의실에 대한 정보가 담겨 있기에 층(세부) 형식으로 사용하고 버릴 것이다.

4. 행복기숙사 행은 버릴 것이다. (인덱스 387 ~ 397)

5. 맵인스쿠에서 강의가 없는 강의실은 검색을 해야만 확인이 가능하다.  강의가 없는 강의실도 검색하지 않아도 보일 수 있게 바꿀지 생각해보아야 한다.

In [11]:
adf2 = adf[['room', 'detail']]
adf2.room = adf2.room + '(' + adf2.detail + ')'
adf2 = adf2.drop('detail', axis=1)
adf2.room = adf2.room.str.replace(' ', '')
adf2

/tmp/ipykernel_419/3463848336.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adf2.room = adf2.room + '(' + adf2.detail + ')'

              room
0     1A103(실험실습실)
1       1A101(사무실)
2       1A102(사무실)
3       1A104(사무실)
4       1A201(사무실)
..             ...
393    549.69(기숙사)
394    549.69(기숙사)
395    549.69(기숙사)
396    549.69(기숙사)
397  1,010.19(기숙사)

[398 rows x 1 columns]